name: gaweid2
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.2+29

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  image_picker: ^0.6.7
  carousel_slider: ^2.2.1
  intl: ^0.15.0
  google_fonts:
  toast: ^0.1.5
  multiselect_formfield: ^0.1.3
  provider: ^5.0.0
  flutter_spinkit: ^4.1.2
  image: ^2.0.5
#  flutter_barcode_scanner: ^1.0.1
  connection_status_bar: ^1.1.2
  flutter_signature_pad: ^2.0.2
  in_app_update: ^2.0.0
  video_player: ^2.1.12
  slide_countdown_clock: ^1.0.3
  url_launcher: ^5.7.10
#  onesignal_flutter: ^2.6.4
  geolocator: ^5.3.2+2
  google_maps_flutter: ^0.5.28+1
  shimmer: ^1.1.2
  flutter_html: ^0.11.0
  flutter_launcher_icons: "^0.8.0"
  change_app_package_name: ^0.1.2
  infinite_scroll_pagination: ^3.0.1
  dropdown_search: ^0.5.0
  youtube_player_flutter: ^8.0.0
  package_info: ^2.0.2
  firebase_remote_config: ^0.6.0
  rating_dialog: ^2.0.1
  comment_box: ^0.0.16
#  flutter_share: ^2.0.0
  uni_links: ^0.4.0
#  flutter_share_me: ^0.9.2
  get: ^4.3.8
  pub_semver: ^2.0.0
  parse_server_sdk: ^2.1.0
  share_plus: ^1.2.0
  path_provider: ^1.6.28
#  new_version: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
     - images/kategori/
     - images/menu/
     - images/menu/1.png
     - images/slider/
     - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
